# Generated by Django 4.0.3 on 2022-07-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_pasword_user_password_product_mini_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
