# Generated by Django 4.0.3 on 2022-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/games/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/games/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/games/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/games/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/games/'),
        ),
    ]
