# Generated by Django 4.0.3 on 2022-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ManyToManyField(to='core.cart'),
        ),
    ]
